# Author: Jeffrey Grover
# Purpose: Config file to edit before running the WGBS workflow Snakefile
# Created: 2019-05-22

# Define sample IDs

samples:
  # Samples should be reported by ID rather than filenames, and exclude the
  # trailing "_1" or "_2", one sample ID per pair. Include the individual
  # .fastq.gz files for each sample in a folder named for just the sample ID.

reference_genome:
    # Path to a bwameth indexed genome here


# Options for individual workflow steps
 
trim_galore:
    adapter_seq : AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
    quality : 20

bwameth:
    threads : 15
    
samtools_sort:
    threads : 5
    mem : 4G

samtools_index:
    threads : 5

methyldackel:
    threads : 5

mosdepth:
    threads : 5
    mapping_quality : 10

# Paths to individual tools
# You probably don't need to change this unless programs are not in your $PATH

paths:
  fastqc_path : fastqc
  trim_galore_path : trim_galore
  bwameth_path : bwameth.py
  samtools_path : samtools
  picard_path : picard
  methyldackel_path : MethylDackel
  mosdepth_path : mosdepth
