# Author: Jeffrey Grover
# Purpose: Config file to edit before running the WGBS workflow Snakefile
# Created: 2019-05-22

# Global variables used for multiple rules

samples:
    - Sample1
    - Sample2
    - etc...
    # Samples should be reported by ID rather than filenames, and exclude the
    # trailing "R1" and "R2", one sample ID per pair. If samples are supplied as
    # separate .fastq.gz files within each pair concatenate them to a single R1 and
    # R2 file prior to running.

reference_genome:
    stuff/bwameth_reference/example_ref.fasta
    # Path to a reference genome here with .fasta extension
    # If indexed, then the index will not be regenerated


# Options for individual workflow steps
# Configure threads for each step as desired, this is a sane starting point

trim_galore:
    adapter_seq : AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
    quality : 20

bwameth:
    threads : 10
    
samtools_sort:
    threads : 5
    mem : 4G

samtools_index:
    threads : 5

methyldackel:
    threads : 5

mosdepth:
    threads : 5
    mapping_quality : 10


# Paths to individual tools
# You probably don't need to change this unless programs are not in your $PATH
# Picard sometimes needs an alias to java -jar /install_dir/picard.jar

paths:
  fastqc_path : fastqc
  trim_galore_path : trim_galore
  bwameth_path : bwameth.py
  samtools_path : samtools
  picard_path : picard
  methyldackel_path : MethylDackel
  mosdepth_path : mosdepth
