# Author: Jeffrey Grover
# Purpose: Config file to edit before running the WGBS workflow Snakefile
# Created: 2019-05-22

# Define sample IDs

samples:

  # Samples should be reported by ID rather than filenames, and exclude the
  # trailing "_1" or "_2", one sample ID per pair

reference_genome : 
    # Path to genome here


# Options for individual workflow steps

trim_galore:
    adapter_seq : AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
    quality : 20

bwameth:
    threads : 15

mark_duplicates:
    picard_path : /usr/local/bin/picard.jar
    
samtools_sort:
    threads : 5

samtools_index:
    threads : 5

methyldackel:
    threads : 5

mosdepth:
    threads : 5
    mapping_quality : 10
